# ----------------------------------------------------------------------------
#
# Package             : bokeh
# Source Repo         : https://github.com/bokeh/bokeh
# Travis Job Link     : https://travis-ci.com/github/asellappen/bokeh/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python

dist: bionic

arch:
 # - amd64
  - ppc64le

matrix:
  include:
  - env: PYTHON_VERSION="3.7"
  #- env: PYTHON_VERSION="3.8"
  #- env: PYTHON_VERSION="3.7"
  #  arch: ppc64le
  - env: PYTHON_VERSION="3.7"
    arch: ppc64le

sudo: required

before_install:
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
#  - bash ci/install_node_modules.sh
  - npm install -g npm
#  - bash ci/install_bokeh_package.sh
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install python=$PYTHON_VERSION pip  pytest-xdist pytest
  
install:
   - pip install -r requirements.txt
 # - python setup.py install
 # - pip install --no-deps -e .


script:
  - python -m pytest -v --tb=short --driver chrome --color=yes tests/integration
  - python -m pytest -v  tests/unit/
  - python -m pytest -v  test_bokehjs.py
